<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!--
        # Собрать всё в правильном порядке
        .\mvnw clean install -DskipTests

        # Запустить gRPC Verification Server (порт gRPC: 9090, HTTP: 8083)
        .\mvnw spring-boot:run -pl grpc-verification-service -am

        # Запустить gRPC Verification Client (RabbitMQ → gRPC → RabbitMQ, HTTP: 8082)
        .\mvnw spring-boot:run -pl grpc-verification-client -am

        # Запустить auction-rest (REST + GraphQL, HTTP: 8080)
        .\mvnw spring-boot:run -pl auction-rest -am

        # Запустить auction-scheduler-service (HTTP: 8084)
        .\mvnw spring-boot:run -pl auction-scheduler-service -am
    -->

    <groupId>edu.rutmiit.demo</groupId>
    <artifactId>auction-rest-root</artifactId>
    <version>1.0</version>
    <packaging>pom</packaging>
    <name>auction-rest [root aggregator]</name>

    <modules>
        <!-- Контракты (библиотеки без main) — собираются первыми -->
        <module>auction-api-contract</module>
        <module>auction-events-contract</module>
        <module>auction-grpc-contract</module>  <!-- НОВЫЙ -->

        <!-- Сервисы — зависят от контрактов -->
        <module>auction-rest</module>
        <module>auction-scheduler-service</module>
        <module>grpc-verification-service</module>   <!-- НОВЫЙ -->
        <module>grpc-verification-client</module>    <!-- НОВЫЙ -->
    </modules>

</project>