# GraphiQL IDE ?????????
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.path=/graphql

# ???????????? GraphQL-????? ??? Spring for GraphQL
spring.graphql.schema.locations=classpath*:graphql/

# ???????????? GraphQL-????? ??? DGS
dgs.graphql.schema-locations=classpath*:graphql/**/*.graphqls

# ???????? ???????????? ?????
spring.graphql.schema.introspection.enabled=true

# CORS ??? GraphQL
spring.graphql.cors.allowed-origins=http://localhost:8080

spring.graphql.graphiql.cdn.enabled=false

server.port=8080

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest