spring:
  application:
    name: grpc-verification-service

server:
  port: ${SERVER_PORT:8083}

grpc:
  server:
    port: ${GRPC_SERVER_PORT:9090}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always