spring:
  application:
    name: grpc-verification-client

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2000
          max-attempts: 3
          multiplier: 2.0

# ИЗМЕНИТЬ НА 8081
server:
  port: 8081

grpc:
  client:
    verification-server:
      host: localhost
      port: 9090

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always